name: cross_lingual_data_augmentation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - nvidia::cudatoolkit=11.3
  - pytorch::pytorch=1.12.1
  - numpy=1.23
  - conda-forge::matplotlib=3.6.0
  - conda-forge::pandas=1.5.0
  - conda-forge::scikit-learn=1.1.2
  - huggingface::transformers=4.24
  - jupyter=1.0.0
  - conda-forge::wandb=0.13.3
  - pip=22.3
  - conda-forge::spacy=3.4
  - huggingface::datasets=2.8.0
  - pip:
     - sentencepiece==0.1.97
     - lightning===1.8.1
     - rouge_score==0.1.2
     - evaluate==0.4.0
